[package]
name = "michigan_jones_platformer_of_doom"
version = "0.1.0"
authors = ["Kristopher Tokarz <kj.tokarz@gmail.com>"]
edition = "2018"

[dependencies]
amethyst = "0.15.3"

[features]
default = ["vulkan"]
empty = ["amethyst/empty"]
metal = ["amethyst/metal"]
vulkan = ["amethyst/vulkan"]